### ISSUE TITLE
[Feature Request]: `match` expression support

### ISSUE THREAD

**Issue by amirmasud** [ondrap/mapbox-filter#1]
Hi dear,

I'd appreciate if you add `match` expression support.

I use openmaptile styles which has `in` and `!in` filter statements. I saw that `filters` are depricated. So, I changed it to `match` expression but unfortunately it's not supported in your app yet.

Thank you!

**Comment by ondrap** [comment]
I have added support for `match`, but didn't test it. Can you test it and let me know?

**Comment by amirmasud** [comment]
Happy New Year and Thanks a lot!

However, it seems it has some sort of problem :thinking:
 
I have the following `match` filter and I get `Parsing mapbox style failed: Error in $.layers[13]: Unknown function name / wrong param count: river` error
```
"filter": [
        "match",
        [
          "get",
          "class"
        ],
        [
          "river",
          "canal",
          "stream"
        ],
        false,
        true
      ],
```
I changed the order of `river` and `canal` and got simillar error for `canal`.

**Comment by ondrap** [comment]
I think this is not correct - it seems to me the correct syntax according to documentation is:

```
"filter": [
        "match",
        [
          "get",
          "class"
        ],
        "river", false,
        "canal", false,
        "stream", false,
        true
      ],
```

**Comment by amirmasud** [comment]
According to the [documentation](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-match), Both of yours and mine is correct:
>Each label must either be a single literal value or an array of literal values (e.g. "a" or ["c", "b"]), and those values must be all strings or all numbers. (The values "1" and 1 cannot both be labels in the same match expression.) 

([this](https://github.com/mapbox/mapbox-gl-js/issues/6144#issuecomment-365333323) and [this](https://gis.stackexchange.com/a/287629/100210) are other examples from mapbox-gl-js contributors)

I can change my style too but it's better to fully support the `match` expression in the code :pray: 

Thanks a lot.

**Comment by ondrap** [comment]
You are right, I missed it. Can you try it now, I have hopefully fixed it.

**Comment by amirmasud** [comment]
Thanks,
Unfortunately I get this error this time:
`mapbox-filter: Parsing mapbox style failed: Error in $.layers[13]: Impossible match label: Fix (UStrArr ["river","canal","stream"])`

(I used the same style as I mentioned before)

**Comment by ondrap** [comment]
Getting there :) Can you try it now?

**Comment by amirmasud** [comment]
Thanks It seems the problem is solved :+1:
