### ISSUE TITLE
equality and inequality expressions

### ISSUE THREAD

**Issue by amirmasud** [ondrap/mapbox-filter#2]
Hi buddy!

I have the following filter in my style but I get `Comparing unequal things: Fix (UApp "get"  (Fix (UStr "subclass"))), Fix (UStr "glacier"): Anyvs. String` error.
```
      "filter": [
        "==",
        [
          "get",
          "subclass"
        ],
        "glacier"
      ],
```
the same problem exists with `!=` expression.

**Comment by ondrap** [comment]
I was too strict on datatypes here, can you try it now?

**Comment by amirmasud** [comment]
The error is disappeared. Thanks :pray:
