### ISSUE TITLE
Support set filters

### ISSUE THREAD

**Issue by lukaswelte** [ondrap/mapbox-filter#5]
First of all, thanks for creating and sharing this tool @ondrap :)

I use a style which has a `in` filter.
This seems not supported right now.

It would be awesome if you could add this, or tell me how to workaround it.
An example is below. It will currently produce `Parsing mapbox style failed: Error in $.layers[X]: Unknown function name / wrong param count: in`

```json
"filter": [
        "all",
        [
          "in",
          "building",
          "cathedral",
          "chapel",
          "church",
          "mosque",
          "temple",
          "synagogue",
          "shrine",
          "civic",
          "hospital",
          "school",
          "stadium",
          "train_station",
          "transportation",
          "university"
        ]
      ]
```

Another example:

```json
"filter": [
        "all",
        [
          "in",
          "highway",
          "primary",
          "trunk"
        ],
        [
          "==",
          "tunnel",
          "yes"
        ]
      ]
```

**Comment by ondrap** [comment]
The `in` is deprecated, I think the replacement is `match`. Could you have a look at the issue #1 , there is alse an example. `match` is supported and should work.

**Comment by lukaswelte** [comment]
Thanks, match works fine.

Sadly e.g. Maputnik, which is quite a popular editor, does not yet use the `expression` style, but the old style of filter.
I can totally understand that it might not be possible to support the deprecated method, but it would be super nice, since tooling is not fully there yet.

The [documentation of the mapbox style](https://docs.mapbox.com/mapbox-gl-js/style-spec/#other-filter) also states that the `filter` syntax will continue to work.

**Comment by ondrap** [comment]
I have added the option to convert the old-style filter to a new-style filter. 
```
mapbox-filter convert-old-filter old_style.json
```

The problem is that you cannot mix old and new-style filteres and there is not an obvious and easy way to detect which style it is. Can you try the conversion tool if it works? (I didn't test it much).
