### ISSUE TITLE
Support filter comparison with number

### ISSUE THREAD

**Issue by lukaswelte** [ondrap/mapbox-filter#6]
Many editors of Mapbox Styles do not care about a difference between number and string for the filters.

So in many style.json there is the following in the filter expression

```json
["==", "layer", 2]
```

When running filter on such a style one received the error `Parsing mapbox style failed: Error in $.layers[X]: Comparing unequal things: Fix (UStr "layer"), Fix (UNum 2.0): Stringvs. Number`

As far as I know the styles the number should always be treated as a string here.
It would be amazing to see this being supported.

**Comment by ondrap** [comment]
Again, this is deprecated syntax. You should use:
```
["==", ["number", ["get", "layer"]], 2 ]
```
Though, I think (I'm not sure), this would actually work:
```
["==", ["get", "layer"], 2 ]
```
