### ISSUE TITLE
`source` and `source-layer` are optional for layer type background

### ISSUE THREAD

**Issue by lukaswelte** [ondrap/mapbox-filter#7]
According to the [style spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layer-source) the source is required except for the background layer (which is nothing but a plain color mostly).

Example:
```json
{
  "id": "background",
  "type": "background",
  "layout": {
    "visibility": "visible"
  },
  "paint": {
    "background-color": "rgba(235, 237, 215, 1)"
  }
}
```

Currently it will error with `Parsing mapbox style failed: Error in $.layers[X]: key "source" not present`

**Comment by ondrap** [comment]
Ok, I will fix this.

**Comment by ondrap** [comment]
Can you try it now? I have updated the package versions, so there will be probably a big rebuild, but it should now accept background layer without a `source`

**Comment by lukaswelte** [comment]
Oh wow that was super fast.

Just tested it and it is working nicely 👍
